# Generated by Django 4.0.6 on 2022-07-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=12)),
                ('twitter', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depoimento', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='depoimento')),
                ('autor', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mensagem')),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('mensagem_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produto', verbose_name='Image do produto')),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='inicio',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='image',
            field=models.ImageField(upload_to='fotos', verbose_name='Image do Inicio'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='text_button',
            field=models.CharField(max_length=20, verbose_name='Texto do Botão'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Titulo do Inicio'),
        ),
    ]
